CREATE TABLE Users(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL UNIQUE,
	Roles BIT NOT NULL, 
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Mail NVARCHAR(60) NOT NULL,
	Addres NVARCHAR(50) NOT NULL,
	Phone NVARCHAR(10) NOT NULL	
);

CREATE TABLE Products(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProductName NVARCHAR(50) NOT NULL,
	Description NVARCHAR(100),
	Price Float NOT NULL,
	Quantity INT NOT NULL,
	Tags NVARCHAR(100)
);

CREATE TABLE Orders(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	States TINYINT NOT NULL CHECK (States >= 0 AND States <= 3),
	Price Float NOT NULL,
	ShippingAdress NVARCHAR(50) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(ID),
);

CREATE TABLE OrderItems(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Quantity INT NOT NULL,
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(ID),
	OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(ID)
);
